# Clase 7

- Map,
- Filter,
- List comprehension
- Lambda
- Apply
- Map

In [75]:
import pandas as pd
import numpy as np

# MAP y FILTER

Función que determina si un número es primo

In [76]:
def es_primo(num):
    '''
    '''
    for n in range(2, num):
        if num % n == 0:
            return False
    return True

In [77]:
lista_1 = [3, 5, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]

Aplicamos la funcion a todos los elementos de la lista

In [79]:
list(map(es_primo, lista_1))

[True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True]

Usamos la función para filtrar la lista y quedarnos solo con los primos

In [80]:
list(filter(es_primo, lista_1))

[3, 5, 11, 13, 17, 19, 23, 29, 31]

Creamos función que eleva al cuadrado

In [81]:
def square(num):
    return num ** 2

Combinamos map y reduce

In [82]:
list(map(square, filter(es_primo, lista_1)))

[9, 25, 121, 169, 289, 361, 529, 841, 961]

# Usamos list comprehension

In [89]:
new_list2 = [square(x) for x in lista_1]

In [86]:
new_list = []
for num in lista_1:
    new_list.append(square(num))

In [91]:
new_list2

[9, 25, 81, 121, 169, 225, 289, 361, 441, 529, 625, 729, 841, 961]

In [92]:
[es_primo(x) for x in lista_1]

[True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True]

In [93]:
[square(x) for x in lista_1 if es_primo(x)]

[9, 25, 121, 169, 289, 361, 529, 841, 961]

# Funciones anónimas

Función que agrega texto

In [94]:
def add_text(x):
    return 'Número {}'.format(x)

In [95]:
add_text(10)

'Número 10'

In [96]:
list(map(add_text, lista_1))

['Número 3',
 'Número 5',
 'Número 9',
 'Número 11',
 'Número 13',
 'Número 15',
 'Número 17',
 'Número 19',
 'Número 21',
 'Número 23',
 'Número 25',
 'Número 27',
 'Número 29',
 'Número 31']

In [97]:
f = lambda x: 'Número {}'.format(x)

In [98]:
[f(x) for x in lista_1]

['Número 3',
 'Número 5',
 'Número 9',
 'Número 11',
 'Número 13',
 'Número 15',
 'Número 17',
 'Número 19',
 'Número 21',
 'Número 23',
 'Número 25',
 'Número 27',
 'Número 29',
 'Número 31']

In [99]:
list(map(lambda x: 'Número {}'.format(x), lista_1))

['Número 3',
 'Número 5',
 'Número 9',
 'Número 11',
 'Número 13',
 'Número 15',
 'Número 17',
 'Número 19',
 'Número 21',
 'Número 23',
 'Número 25',
 'Número 27',
 'Número 29',
 'Número 31']

# Trabajamos con Pandas

In [101]:
casas = pd.read_csv('base_df_junio18.csv', encoding='latin1',
                    na_values='.')

In [102]:
casas

,id,id_tipo,Casa,link,precio,USD,ubica,long,lat,terreno,construc,recam,banios,estac,edad
0,1,1,1,https://casa.metroscubicos.com/MLM-627546314-d...,26900000.0,0,"Cerrada Margaritas 257, Florida, Alvaro Obreg...",-99.180231,19.356287,224.5,NaN,3,4,NaN,NaN
1,2,2,1,https://casa.metroscubicos.com/MLM-632154876-c...,6730000.0,0,"Nabor Carrillo 127, Olivar De Los Padres, Al...",-99.230374,19.332832,170.0,217.00,3,3,3.0,27.0
2,3,3,1,https://casa.metroscubicos.com/MLM-632481484-p...,12000000.0,0,"Nabor Carrillo 37, Olivar De Los Padres, Alv...",-99.230203,19.333523,180.0,320.00,3,5,3.0,3.0
3,4,4,1,https://casa.metroscubicos.com/MLM-632478160-c...,21000000.0,0,"Álvaro Obregón, Distrito Federal., Jardines De...",-99.216546,19.321952,899.0,629.00,3,5,NaN,NaN
4,5,5,1,https://casa.metroscubicos.com/MLM-628596120-e...,26500000.0,0,"Encanto, Florida, Alvaro Obregón, Distrito F...",-99.183862,19.353828,511.0,435.00,3,3,8.0,0.0
5,6,6,1,https://casa.metroscubicos.com/MLM-628367735-c...,6850000.0,0,"La Loma, Lomas De San Angel Inn, Alvaro Obreg...",-99.206959,19.343178,100.0,176.00,3,3,3.0,0.0
6,7,7,1,https://casa.metroscubicos.com/MLM-626989809-r...,9450000.0,0,"Odisea 56, Axomiatla, Alvaro Obregón, Distri...",-99.253536,19.343715,298.0,373.00,4,5,2.0,NaN
7,8,8,1,https://casa.metroscubicos.com/MLM-631593458-s...,31000000.0,0,"Calle Reforma, San Angel, Alvaro Obregón, Di...",-99.192700,19.349600,575.0,375.00,0,2,3.0,0.0
8,9,9,1,https://casa.metroscubicos.com/MLM-626159908-c...,52000000.0,0,"Boulevard De La Luz 0, Pedregal, Alvaro Obreg...",-99.214077,19.324874,1136.0,854.00,4,7,14.0,6.0
9,10,10,1,https://casa.metroscubicos.com/MLM-628692134-p...,6900000.0,0,"Av Toluca 700, Olivar De Los Padres, Alvaro O...",-99.223332,19.335116,161.0,234.00,3,3,3.0,25.0
10,11,11,1,https://casa.metroscubicos.com/MLM-625878522-r...,26500000.0,0,"Cerrada 3, Jardines Del Pedregal, Alvaro Obre...",NaN,NaN,504.0,460.00,4,4,5.0,NaN
11,12,12,1,https://casa.metroscubicos.com/MLM-623079116-c...,16500000.0,0,"Esteros 0, Las Aguilas, Alvaro Obregón, Dist...",-99.201719,19.357149,173.0,400.00,3,3,3.0,0.0
12,13,13,1,https://casa.metroscubicos.com/MLM-627959645-c...,4650000.0,0,"Ricardo Flores Magon 68, Preconcreto, Alvaro ...",-99.212785,19.374555,260.0,276.00,4,2,4.0,30.0
13,14,14,1,https://casa.metroscubicos.com/MLM-628367726-s...,17500000.0,0,"Independencia, Tizapán, Alvaro Obregón, Dist...",-99.198366,19.339237,476.0,486.00,3,3,3.0,0.0
14,15,15,1,https://casa.metroscubicos.com/MLM-624474007-c...,11000000.0,0,"Rio De La Magdalena 200, Progreso Tizapan, Al...",-99.199798,19.336645,259.0,276.00,3,3,2.0,NaN
15,16,16,1,https://casa.metroscubicos.com/MLM-628596039-r...,14800000.0,0,"Las Aguilas, Ampliación Las Aguilas, Alvaro O...",NaN,NaN,568.0,554.00,4,5,5.0,0.0
16,17,17,1,https://casa.metroscubicos.com/MLM-631418554-c...,38000000.0,0,"Álvaro Obregón, Distrito Federal., Jardines De...",-99.215052,19.315413,1800.0,1100.00,4,4,NaN,NaN
17,18,18,1,https://casa.metroscubicos.com/MLM-629431479-c...,1600000.0,1,"Loma, Jardines Del Pedregal, Alvaro Obregón, ...",-99.202387,19.310449,490.0,900.00,4,4,4.0,0.0
18,19,19,1,https://casa.metroscubicos.com/MLM-629933625-c...,13500000.0,0,"Las Aguilas 100, Las Aguilas, Alvaro Obregón,...",-99.208345,19.360535,300.0,300.00,4,3,4.0,NaN
19,20,20,1,https://casa.metroscubicos.com/MLM-631133586-h...,16000000.0,0,"Calzada De Las Aguilas 830 830, Las Aguilas, ...",-99.214692,19.352860,550.0,450.00,3,3,5.0,NaN
20,21,21,1,https://casa.metroscubicos.com/MLM-630580780-s...,1625000.0,1,"Bernardo Quintana 140, Santa Fe, Alvaro Obreg...",NaN,NaN,493.0,485.00,3,4,4.0,NaN
21,22,22,1,https://casa.metroscubicos.com/MLM-628982190-c...,30500000.0,0,"Álvaro Obregón, Distrito Federal., Jardines De...",NaN,NaN,881.0,1098.00,4,5,NaN,NaN
22,23,23,1,https://casa.metroscubicos.com/MLM-627892851-h...,7380000.0,0,"Av. Alfonso Caso Andrade 50, Las Águilas 2o Pa...",-99.206661,19.356980,140.0,160.00,3,,2.0,40.0
23,24,24,1,https://casa.metroscubicos.com/MLM-628957303-c...,34000000.0,0,"Álvaro Obregón, Distrito Federal., Jardines De...",NaN,NaN,1019.0,1300.00,4,5,NaN,NaN
24,25,25,1,https://casa.metroscubicos.com/MLM-629099101-c...,19950000.0,0,"Álvaro Obregón, Distrito Federal., Jardines De...",NaN,NaN,800.0,600.00,3,4,NaN,NaN
25,26,26,1,https://casa.metroscubicos.com/MLM-629375909-c...,1350000.0,1,"Álvaro Obregón, Distrito Federal., Jardines De...",NaN,NaN,828.0,1205.00,5,5,NaN,NaN
26,27,27,1,https://casa.metroscubicos.com/MLM-627349152-c...,21500000.0,0,"Camino De Santa Teresa 1482, Pedregal, Alvaro...",-99.208814,19.309701,720.0,450.00,,,5.0,35.0
27,28,28,1,https://casa.metroscubicos.com/MLM-629098063-c...,1050000.0,1,"Álvaro Obregón, Distrito Federal., Jardines De...",NaN,NaN,576.0,591.00,4,4,NaN,NaN
28,29,29,1,https://casa.metroscubicos.com/MLM-627975109-b...,15000000.0,0,"Cda. De Gómez Farías 0, San Angel, Alvaro Obr...",NaN,NaN,196.0,299.00,3,2,2.0,45.0
29,30,30,1,https://casa.metroscubicos.com/MLM-629431471-v...,34900000.0,0,"Cascada, Jardines Del Pedregal, Alvaro Obregó...",-99.201330,19.326914,900.0,600.00,4,4,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29616,29618,14989,0,https://departamento.metroscubicos.com/MLM-630...,8750000.0,0,"Febo, Florida, Alvaro ObregÃ³n, Distrito Fed...",-99.179617,19.365962,NaN,184.00,3,4,2.0,0.0
29617,29619,14990,0,https://departamento.metroscubicos.com/MLM-630...,1900000.0,0,"Cerrada Xochitl, Miguel Hidalgo, Tlalpan, Di...",-99.180482,19.290788,NaN,59.00,2,1,1.0,0.0
29618,29620,14991,0,https://departamento.metroscubicos.com/MLM-630...,5975000.0,0,"Liverpool 00, JuÃ¡rez, CuauhtÃ©moc, Distrito...",NaN,NaN,NaN,125.00,2,2,2.0,6.0
29619,29621,14992,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29620,29622,14993,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29621,29623,14994,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29622,29624,14995,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29623,29625,14996,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29624,29626,14997,0,https://departamento.metroscubicos.com/MLM-630...,382398.0,0,"Manzanillo 180, Roma Sur, CuauhtÃ©moc, Distr...",-99.164022,19.402926,NaN,70.00,2,1,NaN,NaN
29625,29627,14998,0,https://departamento.metroscubicos.com/MLM-630...,382000.0,0,Calzada Ignacio Zaragoza,-99.082683,19.416072,NaN,60.00,2,2,1.0,NaN
29626,29628,14999,0,https://departamento.metroscubicos.com/MLM-630...,399888.0,0,"Oporto 64 00, San Juan De AragÃ³n, Gustavo ...",-99.092361,19.468630,NaN,60.00,2,1,1.0,NaN
29627,29629,15000,0,https://departamento.metroscubicos.com/MLM-630...,416000.0,0,"Andador Teopancaxco Ed 00, CulhuacÃ¡n Ctm Obre...",-99.116402,19.313695,NaN,64.00,2,1,1.0,NaN
29628,29630,15001,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29629,29631,15002,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29630,29632,15003,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29631,29633,15004,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29632,29634,15005,0,https://departamento.metroscubicos.com/MLM-630...,727333.0,0,"San Simon 00, Narvarte, Benito JuÃ¡rez, Dist...",-99.158069,19.392391,NaN,60.00,2,1,1.0,NaN
29633,29635,15006,0,https://departamento.metroscubicos.com/MLM-630...,770000.0,0,"Ferrocarril Hidalgo 2129, Del Obrero, Gustavo...",-99.090979,19.499645,NaN,55.00,2,1,1.0,NaN
29634,29636,15007,0,https://departamento.metroscubicos.com/MLM-630...,900000.0,0,"Paseo De Los Aztecas 00, San Antonio CulhuacÃ¡...",-99.111722,19.339482,NaN,60.00,2,2,1.0,NaN
29635,29637,15008,0,https://departamento.metroscubicos.com/MLM-630...,950000.0,0,"Fray Servando Teresa De Mier 702, JardÃ­n Balb...",-99.107331,19.415772,NaN,55.00,2,1,1.0,NaN
29636,29638,15009,0,https://departamento.metroscubicos.com/MLM-630...,1165000.0,0,"Rancho Moradores 123, Los Girasoles, CoyoacÃ¡...",-99.124979,19.310724,NaN,65.00,2,1,1.0,NaN
29637,29639,15010,0,https://departamento.metroscubicos.com/MLM-630...,1160000.0,0,"Jaime Torres Bodet 203, Santa MarÃ­a La Ribera...",-99.157107,19.451685,NaN,60.00,2,1,1.0,5.0
29638,29640,15011,0,https://departamento.metroscubicos.com/MLM-630...,1067333.0,0,"Casas Grandes 00, Colonia Del Valle Centro, B...",-99.167713,19.379715,NaN,70.00,2,1,1.0,NaN
29639,29641,15012,0,https://departamento.metroscubicos.com/MLM-630...,1160000.0,0,"Jaime Torres Bodet 203, Santa MarÃ­a La Ribera...",-99.157107,19.451685,NaN,60.00,2,1,1.0,5.0
29640,29642,15013,0,https://departamento.metroscubicos.com/MLM-630...,1160000.0,0,"Jaime Torres Bodet 203, Santa MarÃ­a La Ribera...",-99.157107,19.451685,NaN,60.00,2,1,1.0,5.0
29641,29643,15014,0,https://departamento.metroscubicos.com/MLM-630...,382398.0,0,"Manzanillo 180, Roma Sur, CuauhtÃ©moc, Distr...",-99.164022,19.402926,NaN,70.00,2,1,NaN,NaN
29642,29644,15015,0,https://departamento.metroscubicos.com/MLM-630...,5871000.0,0,"PitÃ¡goras 0, Narvarte Poniente, Benito JuÃ¡r...",-99.157803,19.392752,NaN,156.25,3,3,1.0,NaN
29643,29645,15016,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29644,29646,15017,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29645,29647,15018,0,https://departamento.metroscubicos.com/MLM-630...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Pasamos precios a millones PESOS

In [103]:
casas.loc[casas['USD']==1, 'precio']\
    = casas.loc[casas['USD']==1, 'precio']  * 20

In [105]:
casas['precio'].describe()

count    2.796700e+04
mean     1.517566e+07
std      3.976020e+08
min      1.000000e+00
25%      2.050000e+06
50%      4.520000e+06
75%      1.120000e+07
max      3.600000e+10
Name: precio, dtype: float64

In [106]:
casas['precio'] = casas['precio']/1000000

### Creamos columna de precios con formatio

In [108]:
def format_price(price):
    return '${:,.2}MDP'.format(price)

In [73]:
casas['precio_format'] = casas['precio'].map(format_price)

In [115]:
casas['precio'].map(format_price).head()

0    $2.7e+01MDP
1        $6.7MDP
2    $1.2e+01MDP
3    $2.1e+01MDP
4    $2.6e+01MDP
Name: precio, dtype: object

In [117]:
casas['precio_format'] = casas['precio'].map(
    lambda x: '${:,.3}MDP'.format(x))

In [118]:
casas['precio_format'].head()

0    $26.9MDP
1    $6.73MDP
2    $12.0MDP
3    $21.0MDP
4    $26.5MDP
Name: precio_format, dtype: object

In [127]:
def diff_log(serie):
    '''
    '''
    serie_log = np.log(serie)
    serie_diff = serie_log - serie_log.mean()
    return serie_diff

In [136]:
casas[['precio','construc']].apply(diff_log).head()

     precio  construc
0  1.750838       NaN
1  0.365287  0.189897
2  0.943619  0.576843
3  1.503235  1.251121
4  1.735857  0.883044

In [138]:
def elevar_a_la_tres(x):
    '''
    '''
    return x ** 3
casas[['precio','construc']].applymap(elevar_a_la_tres)

              precio      construc
0       19465.109000           NaN
1         304.821217  1.036023e+07
2        1728.000000  3.307616e+07
3        9261.000000  2.500470e+08
4       18609.625000  8.288186e+07
5         321.419125  5.545233e+06
6         843.908625  5.231362e+07
7       29791.000000  5.315738e+07
8      140608.000000  6.250264e+08
9         328.509000  1.297788e+07
10      18609.625000  9.797218e+07
11       4492.125000  6.448120e+07
12        100.544625  2.125393e+07
13       5359.375000  1.155013e+08
14       1331.000000  2.125393e+07
15       3241.792000  1.709539e+08
16      54872.000000  1.334633e+09
17      32768.000000  7.314327e+08
18       2460.375000  2.727090e+07
19       4096.000000  9.173385e+07
20      34328.125000  1.147913e+08
21      28372.625000  1.327373e+09
22        401.947272  4.173281e+06
23      39304.000000  2.202074e+09
24       7940.149875  2.170818e+08
25      19683.000000  1.754050e+09
26       9938.375000  9.173385e+07
27       9261.000000  2.074747e+08
28       3375.000000  2.700000e+07
29      42508.549000  2.170818e+08
...              ...           ...
29616     669.921875  6.331625e+06
29617       6.859000  2.160000e+05
29618     213.311234  2.000376e+06
29619            NaN           NaN
29620            NaN           NaN
29621            NaN           NaN
29622            NaN           NaN
29623            NaN           NaN
29624       0.055917  3.579110e+05
29625       0.055743  2.269810e+05
29626       0.063946  2.269810e+05
29627       0.071991  2.746250e+05
29628            NaN           NaN
29629            NaN           NaN
29630            NaN           NaN
29631            NaN           NaN
29632       0.384769  2.269810e+05
29633       0.456533  1.756160e+05
29634       0.729000  2.269810e+05
29635       0.857375  1.756160e+05
29636       1.581167  2.874960e+05
29637       1.560896  2.269810e+05
29638       1.215905  3.579110e+05
29639       1.560896  2.269810e+05
29640       1.560896  2.269810e+05
29641       0.055917  3.579110e+05
29642     202.365391  3.888409e+06
29643            NaN           NaN
29644            NaN           NaN
29645            NaN           NaN

[29646 rows x 2 columns]

In [145]:
casas[['precio','construc']].applymap(lambda x: x**3 if x > 100
                                      else x**(0.5)).head()

     precio     construc
0  5.186521          NaN
1  2.594224   10360232.0
2  3.464102   33076161.0
3  4.582576  250047000.0
4  5.147815   82881856.0

In [146]:
f = lambda x, y, z: x+y+z

In [147]:
f(1, 2, 3)

6